[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "SSH Multiplexing"
documentation = "http://rustyhorde.github.io/mussh"
homepage = "http://rustyhorde.github.io/mussh"
keywords = ["mussh", "ssh"]
license = "MIT/Apache-2.0"
name = "mussh"
readme = "README.md"
repository = "https://github.com/rustyhorde/mussh"
version = "0.1.0"

[dependencies]
clap = "~2"
lazy_static = "~0"
rustc-serialize = "~0"
slog = "~1.0.0-alpha"
slog-atomic = "0.3.0"
slog-json = "1.0.0-alpha6"
slog-stream = "1.0.0-alpha6"
slog-term = "~1.0.0-alpha"
ssh2 = "~0"
toml = "~0"

[dependencies.clippy]
optional = true
version = "~0"

[features]
lint = ["clippy"]
