[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "SSH Multiplexing"
documentation = "http://rustyhorde.github.io/mussh"
homepage = "http://rustyhorde.github.io/mussh"
keywords = ["mussh", "ssh"]
license = "MIT/Apache-2.0"
name = "mussh"
readme = "README.md"
repository = "https://github.com/rustyhorde/mussh"
version = "2.0.1"

[dependencies]
chrono = "0.3.0"
clap = "2.22.1"
error-chain = "0.10.0"
serde = "0.9.11"
serde_derive = "0.9.11"
slog-async = "2.0.0-2.0"
slog-term = "2.0.0-2.1"
ssh2 = "0.3.1"
term = "0.4.5"
toml = "0.3.1"

[dependencies.slog]
features = ["max_level_trace", "release_max_level_trace"]
version = "2.0.0-3.0"

[profile.release]
lto = true
