[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "SSH Multiplexing"
documentation = "http://rustyhorde.github.io/mussh"
homepage = "http://rustyhorde.github.io/mussh"
keywords = ["mussh", "ssh"]
license = "MIT/Apache-2.0"
name = "mussh"
readme = "README.md"
repository = "https://github.com/rustyhorde/mussh"
version = "1.0.3-pre"

[dependencies]
clap = "2.20.5"
lazy_static = "0.2.2"
serde = "0.9.9"
serde_derive = "0.9.9"
slog-atomic = "0.4.3"
slog-json = "1.2.1"
slog-stream = "1.2.0"
slog-term = "1.5.0"
ssh2 = "0.3.1"
toml = "0.3.0"

[dependencies.slog]
default-features = false
features = ["max_level_trace", "release_max_level_trace"]
version = "1.5.2"
