[hostlist.all]
hostnames = ["m1", "m2", "m3", "m4", "m6", "m7", "m8", "local"]

[hostlist.i686]
hostnames = ["m1", "m2", "m3"]

[hostlist.local]
hostnames = ["local"]

[hostlist.m1]
hostnames = ["m1"]

[hostlist.m2]
hostnames = ["m2"]

[hostlist.m3]
hostnames = ["m3"]

[hostlist.m4]
hostnames = ["m4"]

[hostlist.m6]
hostnames = ["m6"]

[hostlist.m7]
hostnames = ["m7"]

[hostlist.m8]
hostnames = ["m8"]

[hostlist.most]
hostnames = ["m1", "m2", "m3", "m4", "m6", "m8", "local"]

[hostlist.x86_64]
hostnames = ["local", "m4", "m6", "m7", "m8"]

[hosts.local]
hostname = "localhost"
username = "jozias"

[hosts.m1]
hostname = "10.0.0.3"
username = "jozias"

[hosts.m2]
hostname = "10.0.0.4"
#hostname = "localhost"
#port = 2221
username = "jozias"

[hosts.m3]
hostname = "10.0.0.5"
#hostname = "localhost"
#port = 2222
username = "jozias"

[hosts.m4]
hostname = "10.0.0.60"
#hostname = "localhost"
#port = 2223
username = "jozias"

[hosts.m6]
hostname = "10.0.0.7"
#hostname = "localhost"
#port = 2224
username = "jozias"

[hosts.m7]
hostname = "10.0.0.226"
#hostname = "localhost"
#port = 2225
username = "jozias"

[hosts.m8]
hostname = "10.0.0.242"
#hostname = "localhost"
#port = 2222
username = "kon8116"

[[hosts.m8.alias]]
command = "ls.mac"
aliasfor = "ls"

[cmd.ls]
command = "ls -al"

[cmd."ls.mac"]
command = "ls -alF"

[cmd.uname]
command = "uname -a"
